version: '3.7'

services:

  graphextractor_api:
      image: graph-extract:0.1
      container_name: graphextractor
      build: .
      ports:
        - 80:80
      volumes:
      - ./output:/app/output